name: 'JSTS Quality'
description: 'This action runs ESLint + Reviewdog 🐶 and Prettier.'
inputs:
  github_token:
    description: 'The Github API token needed for Reviewdog and checks.'
  working_directory:
    description: Where is your package.json and therefore your node_modules located.
    required: false
    default: ''
  prettier_target:
    description: 'Where should Prettier look?'
    required: false
    default: './**/*'
  eslint_target:
    description: 'Where should ESLint look?'
    required: false
    default: '.'
  file_extensions:
    description: 'Which file extensions should be considered.'
    required: false
    default: '.js,.jsx,.ts,.tsx,.mjs'

runs:
  using: 'composite'
  steps:

    - name: Install Reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: ESLint
      shell: bash
      run: |
        node_modules/.bin/eslint \
        --format checkstyle \
        --no-error-on-unmatched-pattern \
        --ext ${{inputs.file_extensions}} \
        ${{inputs.eslint_target}} \
        | reviewdog -f=checkstyle -name="eslint" -reporter=github-pr-check || true
      working-directory: ${{ inputs.working_directory }}
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}

    - name: Prettier
      uses: reload/action-prettier@1.0.0
      with:
        github_token: ${{ inputs.github_token }}
        working_directory: ${{ inputs.working_directory }}
        prettier_args: ${{ inputs.prettier_target }}{${{ inputs.file_extensions }}}

branding:
  icon: 'terminal'
  color: 'gray-dark'
